services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: "no"
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq_monitor_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./docker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./docker/startup-rabbitmq.sh:/usr/local/bin/startup-rabbitmq.sh:ro
      - rabbitmq_data:/var/lib/rabbitmq
    command: ["/bin/bash", "/usr/local/bin/startup-rabbitmq.sh"]

volumes:
  rabbitmq_data:
